server:
  port: 51056

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.auto: update
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${JDBC_DATASOURCE_URL:jdbc:mysql://localhost:3306/notification?user=notification_user&password=notification_pw}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      validation-timeout: 5000

  kafka:
    bootstrap-servers:
      - http://localhost:19091
    consumer:
      group-id: ${CONSUMER_GROUP_ID:notification-consumer}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      properties:
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
        spring.json.trusted.packages: "*"
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8086}
        specific.protobuf.value.type: sean.hwang.mockstagram.reaction.event.like.v1.LikeEvent

logging:
  level:
    org.springframework: DEBUG
    com.linecorp.armeria: DEBUG
