### issue 10 years JWT with given userId
POST {{host}}/api/v1/auth/token
Content-Type: application/json

{
  "userId": "1"
}

### mock API requiring authentication
GET {{host}}/api/v1/auth/protected
Authorization: Bearer {{jwt}}
