### like post
POST {{host}}/api/v1/like
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "targetId": "000000000000000000000000",
  "targetType": "LIKE_TARGET_TYPE_POST"
}

### unlike post
POST {{host}}/api/v1/unlike
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "targetId": "000000000000000000000000",
  "targetType": "LIKE_TARGET_TYPE_POST"
}
