version: "3.8"

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "9090:8081"
    volumes:
      - nexus-data:/nexus-data
    restart: always
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1200m -Xmx1200m

volumes:
  nexus-data:
    driver: local
