version: '3.8'
services:
  web-frontend:
    build:
      context: ./web
      dockerfile: ./frontend/Dockerfile
    container_name: mockstagram-web-frontend
    ports:
      - "8081:8081"
    networks:
      - mockstagram-network
  web-bff:
    build:
      context: ./web
      dockerfile: ./bff/Dockerfile
    container_name: mockstagram-web-bff
    ports:
      - "8082:8082"
    networks:
      - mockstagram-network
  mysql:
    image: mysql:8.0
    container_name: mockstagram-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init/mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:6.0
    container_name: mockstagram-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./init/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./init/redis/users.acl:/etc/redis/users.acl  # ACL 파일 추가
      - redis_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes"]  # AOF 활성화로 데이터 영속성 보장
volumes:
  mysql-data:
  redis_data:
networks:
  mockstagram-network:
    driver: bridge