version: '3.8'
services:
  web-frontend:
    build:
      context: ./web
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - mockstagram-network
  web-bff:
    build:
      context: ./web
      dockerfile: ./bff/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - mockstagram-network

networks:
  mockstagram-network:
    driver: bridge