version: '3.8'
services:
  web-bff:
    build:
      context: ./web/bff  # 프로젝트 A의 경로
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # 외부 8081 포트를 컨테이너 8081 포트에 매핑
    networks:
      - mockstagram-network

networks:
  mockstagram-network:
    driver: bridge