### CreateLike
POST {{host}}/like.v1.LikeService/CreateLike
Content-Type: application/json; charset=utf-8; protocol=gRPC

{
  "requester_id": 1,
  "target_id": "67506d607eff4332976ce23d",
  "target_type": "LIKE_TARGET_TYPE_POST"
}

### DeleteLike
POST {{host}}/like.v1.LikeService/DeleteLike
Content-Type: application/json; charset=utf-8; protocol=gRPC

{
  "requester_id": 1,
  "target_id": "67506d607eff4332976ce23d",
  "target_type": "LIKE_TARGET_TYPE_POST"
}
