server:
  port: 50052

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.auto: update
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${JDBC_DATASOURCE_URL:jdbc:mysql://localhost:3306/comment?user=comment_user&password=comment_pw}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      validation-timeout: 5000

  kafka:
    bootstrap-servers:
      - http://localhost:19091
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8086}

logging:
  level:
    org.springframework: DEBUG
    com.linecorp.armeria: DEBUG
